defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: transformer # Change from default group
- training: default
- _self_

data:
   resolution: n320

hardware:
   num_gpus_per_node: 1
   paths:
      output: /mnt/azureml/cr/j/68b11c267ccb4b95bf3497fe77057150/cap/data-capability/wd/output_dir/output
      data: /mnt/azureml/cr/j/68b11c267ccb4b95bf3497fe77057150/cap/data-capability/wd/INPUT_zarr_folder
      graph: /mnt/azureml/cr/j/68b11c267ccb4b95bf3497fe77057150/cap/data-capability/wd/output_dir/graph
   files:
      dataset: noaa-nwm-retro-v2-zarr-pds.zarr
      graph: first_graph_n320.pt

training:
   lr:
      rate: 1e-3
